name: Docker Build and Push

on:
  workflow_dispatch:
  push:
  #   branches:
  #     - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_base

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: get_version
        id: build_version
        run: |
          file_path="pyproject.toml"
          version=$(awk -F ' = ' '$1=="version" {gsub(/"/, "", $2); print $2}' "$file_path")
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: show version
        run: |
          echo ${{ steps.build_version.outputs.VERSION }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Build Base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile_base
          push: true
          # platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/motty-mio2/kb_2315/base:test
            ${{ env.REGISTRY }}/motty-mio2/kb_2315/base:${{ steps.build_version.outputs.VERSION }}

      - name: Build Alembic image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile_alembic
          push: true
          # platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/motty-mio2/kb_2315/alembic:test
            ${{ env.REGISTRY }}/motty-mio2/kb_2315/alembic:${{ steps.build_version.outputs.VERSION }}

      - name: Build FastAPI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile_app
          push: true
          # platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/motty-mio2/kb_2315/app:test
            ${{ env.REGISTRY }}/motty-mio2/kb_2315/app:${{ steps.build_version.outputs.VERSION }}

      - name: Build Streamlit image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile_graph
          push: true
          # platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/motty-mio2/kb_2315/graph:test
            ${{ env.REGISTRY }}/motty-mio2/kb_2315/graph:${{ steps.build_version.outputs.VERSION }}
