name: Docker Build and Push

on:
  workflow_dispatch:
  push:
  #   branches:
  #     - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_base

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: get_version
        id: get_version
        run: |
          python ./get_ver.py >> $GITHUB_OUTPUT

      - name: show version
        run: |
          echo ${{ steps.get_version.outputs }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile_base
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/motty-mio2/kb_2315/base:test
            ${{ env.REGISTRY }}/motty-mio2/kb_2315/base:${{ steps.get_version.outputs }}
